service: pessoa-cadastro-api

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_NAME: h2db.db
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME, 'pessoa-cadastro-db'}
    DATABASE_KEY: ${env:DATABASE_KEY, 'h2db.db'}
    JWT_SECRET: ${env:JWT_SECRET, 'default-secret'}
    JWT_EXPIRES_IN: ${env:JWT_EXPIRES_IN, '1d'}
  memorySize: 512
  timeout: 30
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::${env:S3_BUCKET_NAME, 'pessoa-cadastro-db'}/*"

functions:
  api:
    handler: dist/src/server.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /api/docs
          method: get
      - http:
          path: /api/docs/json
          method: get
    environment:
      NODE_ENV: ${self:provider.stage}

package:
  patterns:
    - '!./**'
    - 'dist/**'
    - 'node_modules/**'
    - 'package.json'
  excludeDevDependencies: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true